server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KHANHAN007/cinego-config-repo
          default-label: main
